/**
 * Generate data/token-storage.js from the benchmark repo's canonical results.
 *
 * Same rule as charts/make_charts.py in the Marp deck: every number on a slide
 * is read from a result file, never typed by hand. Per token-storage/README.md:
 *
 *   ratios  -> 07_kalcher_baseline/results.json :: table1_full_train_consistent
 *   latency -> 03_latency/latency_grid_results.json   (P-core pinned, serving-cold)
 *
 * Usage:  npm run data
 *         TOKEN_STORAGE_REPO=/path/to/token-storage npm run data
 */
import { readFileSync, writeFileSync, existsSync } from 'node:fs'
import { homedir } from 'node:os'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const here = dirname(fileURLToPath(import.meta.url))
const REPO = process.env.TOKEN_STORAGE_REPO || resolve(homedir(), 'projects/token-storage')

const ratioPath = resolve(REPO, '07_kalcher_baseline/results.json')
const latPath = resolve(REPO, '03_latency/latency_grid_results.json')
for (const p of [ratioPath, latPath]) {
  if (!existsSync(p)) {
    console.error(`missing ${p}\nset TOKEN_STORAGE_REPO to the token-storage checkout`)
    process.exit(1)
  }
}

const ratios = JSON.parse(readFileSync(ratioPath, 'utf8'))
  .table1_full_train_consistent.table_median
const lat = JSON.parse(readFileSync(latPath, 'utf8'))

// Palette: grey for byte codecs, Qdrant red for token-native. Same meaning as
// the Marp charts, so the two decks read identically.
const GREY = '#94a3b8'
const RED = '#dc244C'

const CORPORA = [
  ['English', 'prose'],
  ['Code', 'code'],
  ['Hindi', 'hindi'],
]

// The full ladder, in the order the talk climbs it.
const ALL = [
  ['Raw UTF-8', null, GREY],
  ['LZ4', 'LZ4', GREY],
  ['gzip -9', 'gzip-9', GREY],
  ['zstd -19', 'zstd-19', GREY],
  ['brotli q11', 'brotli-q11', GREY],
  ['zstd --train', 'zstd --train', GREY],
  ['r50k raw', 'r50k raw', RED],
  ['o200k raw', 'o200k raw', RED],
  ['o200k +freq', 'o200k +freq', RED],
  ['o200k +ANS', 'o200k +ANS', RED],
]
// Focus: drop the middle byte codecs, keep the comparison that carries the point.
const FOCUS_LABELS = new Set([
  'Raw UTF-8',
  'LZ4',
  'zstd --train',
  'r50k raw',
  'o200k raw',
  'o200k +ANS',
])

const at = (key, corpus) => (key === null ? 1.0 : ratios[key][corpus])

function dataset(label, corpus, rows) {
  const values = rows.map(([, key]) => at(key, corpus))
  return {
    label,
    categories: rows.map(([name]) => name),
    series: [
      {
        name: 'compression ratio',
        values,
        colors: rows.map(([, , c]) => c),
        text: values.map((v) => `${v.toFixed(2)}×`),
        textPosition: 'outside',
      },
    ],
  }
}

const ratioViews = [
  { label: 'All', datasets: CORPORA.map(([l, c]) => dataset(l, c, ALL)) },
  {
    label: 'Focus',
    datasets: CORPORA.map(([l, c]) => dataset(l, c, ALL.filter(([n]) => FOCUS_LABELS.has(n)))),
  },
]

// ── latency, English/o200k, the basis the talk quotes ────────────────────────
const p = lat.grid.prose.o200k
const byte = lat.byte_codecs.prose
const m = p.methods
const round1 = (x) => Math.round(x * 10) / 10

const latency = {
  tokenize: round1(p.tokenize_serving_cold_us[0]),
  detokenize: round1(p.detokenize_serving_cold_us[0]),
  lz4: { compress: round1(byte.LZ4.compress_us[0]), decompress: round1(byte.LZ4.decompress_us[0]) },
  zstd19: {
    compress: round1(byte['zstd-19'].compress_us[0]),
    decompress: round1(byte['zstd-19'].decompress_us[0]),
  },
  raw: { write: round1(m.raw.write_us[0]), read: round1(m.raw.read_us[0]) },
  freq: { write: round1(m['+freq'].write_us[0]), read: round1(m['+freq'].read_us[0]) },
  ans: { write: round1(m['+ANS'].write_us[0]), read: round1(m['+ANS'].read_us[0]) },
}

const out = `// GENERATED by scripts/gen-data.mjs -- do not edit by hand.
// Source: ${ratioPath}
//         ${latPath}
// Regenerate with: npm run data

export const ratioViews = ${JSON.stringify(ratioViews, null, 2)}

export const latency = ${JSON.stringify(latency, null, 2)}
`

const dest = resolve(here, '../data/token-storage.js')
writeFileSync(dest, out)
console.log(`wrote ${dest}`)
console.log(
  `  ratios: r50k raw English ${at('r50k raw', 'prose').toFixed(2)}x, ` +
    `o200k +ANS Hindi ${at('o200k +ANS', 'hindi').toFixed(2)}x`
)
console.log(`  latency: tokenize ${latency.tokenize}us, +freq read ${latency.freq.read}us`)
